version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    restart: always
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./config.yaml:/config.yaml
    command: uwsgi --ini ../uwsgi.ini

volumes:
  pgdata: