version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  web:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      - db
    command: uwsgi --ini ../uwsgi.ini

volumes:
  pgdata: